### PR TITLE
Fix paratest-exasol tests

### PR DESCRIPTION
**Pull request by jirkasemmler**
Jira: KBC-XXX

just using buckets for para tests -> fixing exa suite which fails in last days...

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

### CODE REVIEW

**Comment by jirkasemmler** [comment]
vycuknul jsem to z https://github.com/keboola/storage-api-php-client/pull/964 , bo ten se asi chvilku potahne toto nas prudi s kazdym signoffem

**Review by zajca — APPROVED** [review]
Asi dobrý nenapadá mě proč to není v paratestu, ale pokud to má důvod tak sa ho brzo dozvíme :)

**Comment by jirkasemmler** [comment]
> 

tak uz jsem to nasel... padaj tam testy na workspacech potom... ta trida ExportParamsTest se totiz pouziva nekdy v paratestu a nekdy ne... boha ...

image

**Comment by jirkasemmler** [comment]
vyerseno tady https://github.com/keboola/storage-api-php-client/pull/1002/files

**Pull request closed without merging**
