### PR TITLE
SOX-397 SOX external buckets tests

### PR DESCRIPTION
**Pull request by zajca**
Jira: SOX-397
KBC: XXX

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

### CODE REVIEW

**Comment by romanbracinik** [comment]
👁️

**Review by romanbracinik — CHANGES_REQUESTED** [review]
Hmm ty jo na tejto branchi mi zacali padat povodne testy pre ne-SOX bq
Screenshot 2023-10-19 at 9 29 42
Screenshot 2023-10-19 at 9 32 41

**Comment by zajca** [comment]
> Hmm ty jo na tejto branchi mi zacali padat povodne testy pre ne-SOX bq Screenshot 2023-10-19 at 9 29 42 Screenshot 2023-10-19 at 9 32 41

Whát, to sů nějaké nové testy, ty sem tam neměl :)

**Comment by romanbracinik** [comment]
A jo sakra sry to som si nevsimol ja som si to rebasol pretoze to tu nebolo aktualne ale uz som si nevsimol, ze tam boli zrovna novinky na tomto mieste

**Comment by romanbracinik** [comment]
👁️

**Review by romanbracinik — APPROVED** [review]
👌

**Pull request merged**
