### PR TITLE
Fix order of parameters in join function

### PR DESCRIPTION
**Pull request by ujovlado**

### CODE REVIEW

**Comment by Halama** [comment]
Mas k tomu nejaky test? Co to zpusobovalo?

**Comment by Halama** [comment]
ono to koukam funguje i když se dají obráceně ty parametry :)

**Comment by Halama** [comment]
```implode() can, for historical reasons, accept its parameters in either order. For consistency with explode(), however, it may be less confusing to use the documented order of arguments.```
ok :)

**Comment by ujovlado** [comment]
pustal som testy `docker-bundle` a obcas mi to vyhodilo `Array to string conversion` ... potom som to fixol tymto PR, no uz sa mi to nepodarilo dostat znovu do toho stavu. :)

Boli to testy `testExecutorInvalidInputMapping` a `testExecutorInvalidInputMapping2`:
https://github.com/keboola/docker-bundle/blob/273495a/Tests/Functional/DataLoaderTest.php#L144

**Comment by ujovlado** [comment]
^len ten testExecutorInvalidInputMapping2

**Comment by Halama** [comment]
to imho nemohlo souviset. Tamto se testuje porad.

**Comment by ujovlado** [comment]
no jo, ale ci sa to testuje so zapnutym error_reportingom :)

**Comment by ujovlado** [comment]
este to niekedy vyskusam

**Pull request merged**
