### PR TITLE
Test creating new version for config

### PR DESCRIPTION
**Pull request by fejjo**
Jira: KBC-1197
Main PR: https://github.com/keboola/connection/pull/2997
Before asking for review make sure that:

- [x] New client method(s) has tests 
- [x] Apiary file is updated - updatol by som az po tom ako sa odstrani featura
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

### CODE REVIEW

**Review by tomasfejfar — CHANGES_REQUESTED** [review]
IMHO je potřeba ty testy postavit tak, aby běžely jednou bez featury a jednou s featurou.

**Comment by fejjo** [comment]
Jo jasne na to som zabudol upravim to, dik.

**Comment by fejjo** [comment]
@tomasfejfar asi by som to hodil len ako dalsiu "suite" https://github.com/keboola/connection/pull/2997/commits/a7841be772ddd15cd6f49fa5a94e49f8c7f55b81

**Review by tomasfejfar — DISMISSED** [review]
Chybí tomu výhybka pro situaci, kdy ta věc nemá feature (test musí být zabalený v nějakém `if(getenv(...))`

**Comment by fejjo** [comment]
Je potreba v clientovy este pridat `IS_VERSIONS_LIST_IMPLEMENTED_FOR_DEV_BRANCH=true`

**Review by ErikZigo — APPROVED** [review]

**Comment by fejjo** [comment]
rebase

**Pull request merged**
