### PR TITLE
test few default values for datatypes, more is tested in driver

### PR DESCRIPTION
**Pull request by romanbracinik**
Jira: BIG-208
KBC:  https://github.com/keboola/connection/pull/4770

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

### CODE REVIEW

**Review by jirkasemmler — APPROVED** [review]
lgtm. prosim tagni to

**Comment by jirkasemmler** [comment]
jeste v souvislosti s https://github.com/keboola/php-storage-driver-bigquery/pull/102#pullrequestreview-1791107351 me napada, jestli by tady ta sada testu nemela byt ve vyslekdu kompletni, stejne jako u snflk

**Comment by romanbracinik** [comment]
> jeste v souvislosti s [keboola/php-storage-driver-bigquery#102 (review)](https://github.com/keboola/php-storage-driver-bigquery/pull/102#pullrequestreview-1791107351) me napada, jestli by tady ta sada testu nemela byt ve vyslekdu kompletni, stejne jako u snflk

Asi jo nechcel som sem cpat vsetko z dovodu dlzky, ale ked nad tim teraz premyslam asi by to tu malo byt. Pridam to.

**Comment by romanbracinik** [comment]
Dopisal som tie testy aj do SAPI

**Review by jirkasemmler — APPROVED** [review]
super, ze tam mame cely set

**Pull request merged**
