### PR TITLE
KBC-2761 migrate DevBranches to JSON

### PR DESCRIPTION
**Pull request by martinjunger**
Jira: KBC-2761

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

### CODE REVIEW

**Comment by tomasfejfar** [comment]
Potřebuje rebase IMHO

**Comment by martinjunger** [comment]
[Tag](https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=25885&view=results) prosel 🟢

**Review by fejjo — COMMENTED** [review]
trochu sa mi nezda ten label patch (backwards compatible fix) menis napr ze delete nevrati nic alebo pridavas ze metody vracaju array ked dovtedy nemaly type hint nemoze to nieco teoreticky rozbit? Ale fajn ze testy presli

**Comment by martinjunger** [comment]
> trochu sa mi nezda ten label patch (backwards compatible fix) menis napr ze delete nevrati nic alebo pridavas ze metody vracaju array ked dovtedy nemaly type hint nemoze to nieco teoreticky rozbit? Ale fajn ze testy presli

Label `patch` je podle me dostatecny (vsechny ostatni PR ho maji taky. Na label `minor` (new feature) uz to podle me neni. Ale asi ho tam muzu klidne dat, pro jistotu.

**Review by fejjo — APPROVED** [review]
Ok

**Pull request merged**
