### PR TITLE
BIG-105 delete rows

### PR DESCRIPTION
**Pull request by zajca**
Jira: BIG-105

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

### CODE REVIEW

**Comment by martinjunger** [comment]
> > > Zamerne jsi vynechal tenhle test `\Keboola\Test\Backend\CommonPart2\SlicedImportsTest::testInvalidFilesInManifest`?
> > > ```
> > >     public function testInvalidFilesInManifest(): void
> > >     {
> > >         $this->skipTestForBackend([
> > >             self::BACKEND_TERADATA, // TODO driver probably wont check manifest
> > >             self::BACKEND_BIGQUERY,
> > >         ], 'Rows delete supported');
> > > ```
> > 
> > 
> > Tam je špatná message imho šak to nikde nevolá ty delete rows, ne?
> 
> Aha sorry je tam akorát mě teda na BQ ten test nepadá :D

Tak muzes dat pryc to omezeni na BQ, ne?

**Comment by zajca** [comment]
> > > > Zamerne jsi vynechal tenhle test `\Keboola\Test\Backend\CommonPart2\SlicedImportsTest::testInvalidFilesInManifest`?
> > > > ```
> > > >     public function testInvalidFilesInManifest(): void
> > > >     {
> > > >         $this->skipTestForBackend([
> > > >             self::BACKEND_TERADATA, // TODO driver probably wont check manifest
> > > >             self::BACKEND_BIGQUERY,
> > > >         ], 'Rows delete supported');
> > > > ```
> > > 
> > > 
> > > Tam je špatná message imho šak to nikde nevolá ty delete rows, ne?
> > 
> > 
> > Aha sorry je tam akorát mě teda na BQ ten test nepadá :D
> 
> Tak muzes dat pryc to omezeni na BQ, ne?

No napsal sem to blbě test padá protože nepadá poslední api call, který spadnůt má :D

**Comment by martinjunger** [comment]
> > > > > Zamerne jsi vynechal tenhle test `\Keboola\Test\Backend\CommonPart2\SlicedImportsTest::testInvalidFilesInManifest`?
> > > > > ```
> > > > >     public function testInvalidFilesInManifest(): void
> > > > >     {
> > > > >         $this->skipTestForBackend([
> > > > >             self::BACKEND_TERADATA, // TODO driver probably wont check manifest
> > > > >             self::BACKEND_BIGQUERY,
> > > > >         ], 'Rows delete supported');
> > > > > ```
> > > > 
> > > > 
> > > > Tam je špatná message imho šak to nikde nevolá ty delete rows, ne?
> > > 
> > > 
> > > Aha sorry je tam akorát mě teda na BQ ten test nepadá :D
> > 
> > 
> > Tak muzes dat pryc to omezeni na BQ, ne?
> 
> No napsal sem to blbě test padá protože nepadá poslední api call, který spadnůt má :D

Jo, na TD to pada taky. A na SNFLK to prochazi.
Napada te, jaka by teda mela byt ta message?
`Read files from manifest is not supported.`

**Review by martinjunger — APPROVED** [review]
LGTM

**Pull request merged**
