### PR TITLE
Roman fix slicing uploads handle promise and retry

### PR DESCRIPTION
**Pull request by fejjo**
Jira: KBC-XXX

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

### CODE REVIEW

**Comment by fejjo** [comment]
tag presiel tu https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=24746&view=logs&j=ae13dfb3-00c3-5552-9b00-63e26024fcba&t=48e25ff6-be86-558e-50b2-b8f91a4d5f0f

**Comment by jirkasemmler** [comment]
pridal jsem testik, jen co projde build tak to mergnu a vydam. cc @ErikZigo

**Comment by ErikZigo** [comment]
@jirkasemmler ok super, diky za zpravu

**Review by jirkasemmler — APPROVED** [review]
:+1:

**Pull request merged**
