### PR TITLE
KBC-2540 snizit timeout v SAPI clientovi

### PR DESCRIPTION
**Pull request by tomasfejfar**
Jira: KBC-2540

Before asking for review make sure that:

- [x] New client method(s) has tests
- [x] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

### CODE REVIEW

**Comment by tomasfejfar** [comment]
Default timeout jsem nechal 60s což by mělo být dost na všechno možné i nemožné. Na zakládání workspacu je 7200s dál. A na mazání je 7200s dál (někde tam něco trvá ve spořitelně prý). Ale dá se to upravovat jak per-http-method, tak se dá injectnout prodloužení přímo v metodě klienta.

**Comment by MiroCillik** [comment]
Vyzera to fajn, ale si si isty, ze ten middleware tam nastavi ten default 60s pre vsetky requesty? Neprebije to tohle?
https://github.com/keboola/storage-api-php-client/pull/785/files#diff-f1f1f328092455d95f0d3a1c5cbe7e0f9e7f47d5d7964b4acd93e0c952cd7193R2278
Respektive je to tam vobec potreba este nechavat?

Dal by sa spravit nejaky test, ze to pri zavolani Client::request() bude mat nastaveny spravny timeout? Ta metoda je zrovna protected takze to moc otestovat nepojde asi...

**Review by MiroCillik — COMMENTED** [review]
Viz moj koment

**Review by zajca — APPROVED** [review]
:ok_man:

**Comment by Halama** [comment]
Ta default minuta mi přijde málo když se podívám na https://app.datadoghq.eu/apm/traces?query=%40_top_level%3A1%20service%3Aconnection%20operation_name%3Azf1.request%20-env%3Aconnection-testing%20-resource_name%3A%22workspaces%40delete%20storageApiVersioned2%22&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2C%40_duration.by_service%2Cenv&historicalData=true&messageDisplay=inline&sort=desc&spanViewType=metadata&start=1649184185324&end=1649788985324&paused=false

Kde se v tom klientovi zaklada config workspace? tam by ten extended timeout mel byt taky 
image

Takhle teda ofiltrovane bez tech co by mely mit extended timeout: https://app.datadoghq.eu/apm/traces?query=%40_top_level%3A1%20service%3Aconnection%20operation_name%3Azf1.request%20-env%3Aconnection-testing%20-resource_name%3A%28%22workspaces%40delete%20storageApiVersioned2%22%20OR%20%22components%40post-configs-workspaces%20storageApiVersioned2%22%29&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2C%40_duration.by_service%2Cenv&historicalData=true&messageDisplay=inline&sort=desc&spanViewType=metadata&start=1649184364919&end=1649789164919&paused=false

image

**Comment by MiroCillik** [comment]
Tu sa vytvara ten config workspace https://github.com/keboola/storage-api-php-client/blob/master/src/Keboola/StorageApi/Components.php#L329

**Pull request merged**
