### PR TITLE
check metadata in create from workspace test

### PR DESCRIPTION
**Pull request by pivnicek**
parent https://github.com/keboola/connection/issues/1430

### CODE REVIEW

**Comment by pivnicek** [comment]
@yustme fyi, tohle jsou testy pro https://github.com/keboola/connection/pull/1792

**Comment by pivnicek** [comment]
https://github.com/keboola/storage-api-php-client/pull/275This doesn't work, RS and SNFLK need separate tests

**Comment by yustme** [comment]
@pivnicek it's closed. I suppose review is not required ?

**Comment by pivnicek** [comment]
sorry, yes, this was replaced by https://github.com/keboola/storage-api-php-client/pull/275

**Pull request closed without merging**
