### PR TITLE
CT-1259 delete table rows request validation

### PR DESCRIPTION
**Pull request by martinjandl**
Jira: CT-1259
KBC: https://github.com/keboola/connection/pull/4906

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

### CODE REVIEW

**Review by jirkasemmler — APPROVED** [review]
ok, jen to pak asi bude potrebovat zmenu az upravis https://github.com/keboola/connection/pull/4906/files#r1529930970

**Comment by jirkasemmler** [comment]
btw @martinjandl jak dopadne https://github.com/keboola/storage-api-php-client/blob/16ab2ffcafcfc157a95a869543127ad603e71ee4/tests/Backend/CommonPart1/DataPreviewLimitsTest.php#L88 ? nebude tam problem, ze to vrati vic validacnich chyb? prosim pust to.

jo a toto prosim neni `patch`, ale `no-release`. Tady neni zadna zmena, je to jen uprava testu

**Comment by martinjandl** [comment]
Dobehne ok.
Ten test [DataPreviewLimitsTest.php](https://github.com/keboola/storage-api-php-client/blob/16ab2ffcafcfc157a95a869543127ad603e71ee4/tests/Backend/CommonPart1/DataPreviewLimitsTest.php#L88) neni upravou dotcen, je tam pouzity whereFilters, ktery je validovan ParamWhereFilters

**Review by jirkasemmler — APPROVED** [review]

**Review by romanbracinik — APPROVED** [review]
lgtm pred mergom nezabudni na https://github.com/keboola/connection/pull/4906#issuecomment-2012888212

**Review by jirkasemmler — APPROVED** [review]

**Pull request merged**
