### PR TITLE
Update test and docs (128px icon)

### PR DESCRIPTION
**Pull request by ujovlado**
Jira: https://keboola.atlassian.net/browse/KBCP-1666

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
  - no new methods
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

---

Len doplneny test a mensi update docs

### CODE REVIEW

**Review by romanbracinik — APPROVED** [review]
lgtm

**Comment by ujovlado** [comment]
Dal som rebase, ale este sa bavim so @zajca, ze prihodime jedno typo

**Comment by zajca** [comment]
@ujovlado není to spíš patch enom, nez minor?

**Comment by ujovlado** [comment]
> @ujovlado není to spíš patch enom, nez minor?

Tak z pohladu clienta je to patch. Z pohladu connection minor. Dam patch, ok.

**Comment by zajca** [comment]
Spadl na tom ten test https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=27208&view=logs&j=ae13dfb3-00c3-5552-9b00-63e26024fcba&t=48e25ff6-be86-558e-50b2-b8f91a4d5f0f&l=3980 K tomu je ještě PR v connection?

**Comment by ujovlado** [comment]
Jj, pisal som ti to na Slack, vedel som ze to spadne, ked sa to merglo bez toho ;)

**Pull request merged**
